services:
  web:
    image: easycron-services:latest
    command: ['node', 'server.js']
    env_file:
      - .env.compose
    ports:
      - '3000:3000'
    restart: on-failure

  worker:
    image: easycron-services:latest
    command: ['node', 'dist/worker/index.js']
    env_file:
      - .env.compose
    restart: on-failure
    healthcheck:
      test: ['CMD', 'node', '-e', 'process.exit(0)']
      interval: 30s
      timeout: 3s
      retries: 3

  scheduler:
    image: easycron-services:latest
    command: ['node', 'dist/scheduler/index.js']
    env_file:
      - .env.compose
    restart: on-failure
    healthcheck:
      test: ['CMD', 'node', '-e', 'process.exit(0)']
      interval: 30s
      timeout: 3s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: redis
    env_file:
      - .env.compose
    restart: unless-stopped
    command: ['redis-server', '--requirepass', 'mysecretpassword']
    volumes:
      - redis_data_local:/data

networks:
  default:
    driver: bridge

volumes:
  redis_data_local:
    driver: local
