name: Build and Deploy Production

on:
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: production

    steps:
      - name: Set up Docker image tags
        id: vars
        run: |
          echo "TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Load 1password secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          DOCKER_USERNAME: 'op://easycron-app/github-secrets/DOCKER_USERNAME'
          DOCKER_PASSWORD: 'op://easycron-app/github-secrets/DOCKER_PASSWORD'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push docker image
        run: |
          docker build -t ghcr.io/${{ env.DOCKER_USERNAME }}/easycron:${{ env.TAG_VERSION }} -t ghcr.io/${{ env.DOCKER_USERNAME }}/easycron:latest . && \
          docker push ghcr.io/${{ env.DOCKER_USERNAME }}/easycron:${{ env.TAG_VERSION }} && \
          docker push ghcr.io/${{ env.DOCKER_USERNAME }}/easycron:latest

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: production
    needs: build

    steps:
      - name: Set up Docker image tags
        id: vars
        run: |
          echo "TAG_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Load 1password secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          REMOTE_HOST: 'op://easycron-app/github-secrets/REMOTE_HOST'
          REMOTE_USER: 'op://easycron-app/github-secrets/REMOTE_USER'
          DOCKER_USERNAME: 'op://easycron-app/github-secrets/DOCKER_USERNAME'
          DOCKER_PASSWORD: 'op://easycron-app/github-secrets/DOCKER_PASSWORD'
          SSH_PRIVATE_KEY: 'op://easycron-app/github-secrets/SSH_PRIVATE_KEY'

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.REMOTE_HOST }}
          username: ${{ env.REMOTE_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            cd /home/jack/easycron
            git pull

            export OP_SERVICE_ACCOUNT_TOKEN=${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
            echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

            ENVIRONMENT=production op inject -f -i .env.op -o .env
            echo "TAG_VERSION=${{ env.TAG_VERSION }}" >> .env

            docker pull ghcr.io/${{ env.DOCKER_USERNAME }}/easycron:${{ env.TAG_VERSION }}

            export $(grep -v '^#' .env | xargs) && \
            envsubst < docker-compose.production.yml | docker stack deploy --with-registry-auth -c - easycron && \
            docker system prune -f
